version: '3.9'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: pg
      POSTGRES_DB: code
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/tmp/pgdata

  
  redis_cache:
    image: "redis:alpine"

  celery_beat:
    build: .
    entrypoint: celery -A code_service worker -B
    depends_on:
      - db
      - redis_cache

  code_service_migration:
    build: .
    entrypoint: python manage.py migrate
    depends_on:
      - db
      - redis_cache

  code_service:
    build: .
    entrypoint: python manage.py runserver 0.0.0.0:3012
    ports:
      - "3012:3012"
    depends_on:
      - db
      - redis_cache
      - code_service_migration

volumes:
  postgres_data: