caches:
  backend: 'django_redis.cache.RedisCache'
  options:
    client_class: 'django_redis.client.DefaultClient'
    ignore_exceptions: True
    parser_class: 'redis.connection.HiredisParser'

youtube_query_string: 'fampay'
youtube_keys:
  - 'AIzaSyBUk_Gutur67QaJd0DJDMTgvPSbKfjTEKo'
